-- Autor: Athan Espinoza

-- Hallazgo de seguridad (auditoría 2026-08-12, H-08): no existía ninguna
-- forma de revocar un token SCIM comprometido vía API — la columna
-- `scim_tokens.revoked_at` existe desde F-18 (0021_scim.sql) pero nada la
-- escribía. Se agrega el evento de auditoría correspondiente; 'scim_token.revoked'
-- se había retirado del catálogo en 0023 justamente porque no existía código
-- que lo emitiera (ver comentario ahí) — ahora sí, con el nombre correcto
-- consistente con el resto del namespace 'scim.*' (`scim.token_created`).
alter table audit_log_entries drop constraint audit_log_entries_event_type_check;
alter table audit_log_entries add constraint audit_log_entries_event_type_check check (event_type in (
    'auth.login_succeeded',
    'auth.login_failed',
    'auth.device_unrecognized',
    'auth.device_verified',
    'auth.device_verification_failed',
    'auth.device_auto_verified_no_smtp',
    'auth.logout',
    'auth.mfa_failed',
    'permission.granted',
    'group.member_added',
    'group.member_removed',
    'group.manager_changed',
    'resource.created',
    'device.trusted',
    'device.revoked',
    'device.approval_granted',
    'metadata_key.created',
    'metadata_key.rotation_started',
    'metadata_key.member_added',
    'role.created',
    'role.permissions_updated',
    'device_approval_policy.updated',
    'mfa.enrolled',
    'mfa_policy.updated',
    'account_recovery_policy.updated',
    'account_recovery.enrolled',
    'account_recovery.requested',
    'account_recovery.approved',
    'account_recovery.rejected',
    'account_recovery.completed',
    'password_policy.updated',
    'retention_policy.updated',
    'retention.purge_ran',
    'emergency_access.designated',
    'emergency_access.requested',
    'emergency_access.approved',
    'emergency_access.rejected',
    'emergency_access.accepted',
    'emergency_access.revoked',
    'emergency_access.granted_by_timeout',
    'emergency_access_policy.updated',
    'user.deactivated',
    'user.activated',
    'user.purged',
    'sso.config_updated',
    'sso.login_succeeded',
    'sso.jit_provisioned',
    'sso.account_linked',
    'sso.link_rejected_unverified_email',
    'scim.token_created',
    'scim.token_revoked',
    'scim.user_created',
    'scim.user_updated',
    'scim.user_deactivated',
    'directory_sync.config_updated',
    'directory_sync.dry_run',
    'directory_sync.applied',
    'external_share.created',
    'external_share.accessed',
    'external_share.revoked',
    'external_share.burned',
    'external_share_policy.updated',
    'export_policy.updated',
    'export.performed',
    'import.performed',
    'users.exported',
    'groups.exported',
    'backup.created',
    'backup.failed',
    'backup.restored',
    'restore.failed',
    'cli.cleanup_ran',
    'cli.user_promoted',
    'cli.recovery_setup_issued',
    'passkey.revoked',
    'resource.updated',
    'smtp_config.updated',
    'user.passphrase_changed',
    'self_registration_policy.updated',
    'user.email_verified',
    'resource.deleted',
    'recovery_kit.generated',
    'recovery_kit.reset_requested',
    'recovery_kit.reset_completed',
    'recovery_kit.reset_mfa_failed',
    'sharing_policy.updated',
    'group.share_exempt_changed'
));
